openapi: 3.0.3
info:
  title: P2P Lending Platform API (MVP)
  version: 0.1.0
  description: >
    核心域服务开放接口；遵循假设 A1~A6。除 GET 外默认需要 JWT（Borrower 或 Admin 作用域），
    放/还款与合同相关接口必须带 X-Idempotency-Key。
servers:
  - url: https://api.sme-loan.example.com
    description: Production (UTC+0)
  - url: https://sandbox-api.sme-loan.example.com
    description: Sandbox
tags:
  - name: Auth
  - name: Users
  - name: Risk
  - name: Loans
  - name: Payments
  - name: Ledger
  - name: Collections
  - name: Notifications
  - name: Channels
  - name: Reports
paths:
  /auth/otp:
    post:
      tags: [Auth]
      summary: 请求 OTP（假设 A5）
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [phone, countryCode, channel]
              properties:
                phone: { type: string, pattern: "^[0-9]{6,15}$" }
                countryCode: { type: string, example: "+233" }
                channel: { type: string, enum: [sms, whatsapp] }
      responses:
        "200":
          description: OTP 请求成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  requestId: { type: string }
                  expireAt: { type: string, format: date-time }
        "429": { $ref: "#/components/responses/TooManyRequests" }
      x-permissions: [{ role: anonymous, scope: public.app }]
  /auth/token:
    post:
      tags: [Auth]
      summary: OTP 换取 JWT
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [requestId, otpCode, deviceId]
              properties:
                requestId: { type: string }
                otpCode: { type: string, minLength: 4, maxLength: 6 }
                deviceId: { type: string }
      responses:
        "200":
          description: 返回访问令牌
          content:
            application/json:
              schema:
                type: object
                properties:
                  accessToken: { type: string }
                  refreshToken: { type: string }
                  expiresIn: { type: integer }
        "401": { $ref: "#/components/responses/Unauthorized" }
      x-permissions: [{ role: borrower, scope: borrower.auth }]
  /users/me:
    get:
      tags: [Users]
      summary: 查询当前借款人档案
      responses:
        "200":
          description: 用户详情
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserProfile"
      security: [{ BorrowerJWT: [] }]
      x-permissions: [{ role: borrower, scope: borrower.profile }]
  /users/{userId}/kyc:
    put:
      tags: [Users]
      summary: 上传并更新 KYC 元数据（OCR/活体结果）
      parameters:
        - $ref: "#/components/parameters/UserId"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/KycPayload"
      responses:
        "202": { description: 已接受，异步校验 }
      security: [{ BorrowerJWT: [] }]
      x-permissions: [{ role: borrower, scope: borrower.kyc }]
  /risk/evaluations:
    post:
      tags: [Risk]
      summary: 触发机审（loan-svc 调用）
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RiskEvaluationRequest"
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/RiskEvaluationResult"
        "422": { $ref: "#/components/responses/Unprocessable" }
      security: [{ ServiceJWT: [] }]
      x-permissions: [{ role: service, scope: risk.evaluate }]
  /loans:
    post:
      tags: [Loans]
      summary: 创建贷款申请（草稿）
      parameters:
        - $ref: "#/components/parameters/IdempotencyKey"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/LoanApplicationDraft"
      responses:
        "201":
          description: 创建成功
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/LoanSummary"
        "409": { $ref: "#/components/responses/Conflict" }
      security: [{ BorrowerJWT: [] }]
      x-permissions: [{ role: borrower, scope: borrower.loan }]
  /loans/{loanId}/submit:
    post:
      tags: [Loans]
      summary: 提交贷款申请进入风控
      parameters:
        - $ref: "#/components/parameters/LoanId"
        - $ref: "#/components/parameters/IdempotencyKey"
      responses:
        "202": { description: 已提交进入 AUTO_CHECKING }
      security: [{ BorrowerJWT: [] }]
      x-permissions: [{ role: borrower, scope: borrower.loan }]
  /loans/{loanId}/contracts:
    get:
      tags: [Loans]
      summary: 获取合同快照
      parameters:
        - $ref: "#/components/parameters/LoanId"
      responses:
        "200":
          content:
            application/json:
              schema:
                type: object
                properties:
                  contractUrl: { type: string, format: uri }
                  version: { type: string }
      security: [{ BorrowerJWT: [] }, { AdminJWT: [] }]
      x-permissions:
        - { role: borrower, scope: borrower.contract }
        - { role: admin, scope: loan.review }
  /payments/disbursements:
    post:
      tags: [Payments]
      summary: 触发放款
      parameters:
        - $ref: "#/components/parameters/IdempotencyKey"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/DisbursementRequest"
      responses:
        "202": { description: 已发送到通道 }
      security: [{ ServiceJWT: [] }]
      x-permissions: [{ role: service, scope: payment.disburse }]
  /payments/repayments:
    post:
      tags: [Payments]
      summary: 记账还款（主动或回调）
      parameters:
        - $ref: "#/components/parameters/IdempotencyKey"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RepaymentRequest"
      responses:
        "201": { description: 还款已登记 }
      security: [{ ServiceJWT: [] }]
      x-permissions: [{ role: service, scope: payment.repay }]
  /ledger/entries:
    post:
      tags: [Ledger]
      summary: 创建双分录台账
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/LedgerEntry"
      responses:
        "201": { description: 记账成功 }
        "409": { $ref: "#/components/responses/Conflict" }
      security: [{ ServiceJWT: [] }]
      x-permissions: [{ role: service, scope: ledger.write }]
  /collections/cases:
    post:
      tags: [Collections]
      summary: 建案（由贷款事件或人工触发）
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CollectionCaseCreate"
      responses:
        "201": { description: 案件已创建 }
      security: [{ ServiceJWT: [] }, { AdminJWT: [] }]
      x-permissions:
        - { role: service, scope: collection.auto }
        - { role: admin, scope: collection.manage }
  /collections/cases/{caseId}/actions:
    post:
      tags: [Collections]
      summary: 记录跟进动作/PTP
      parameters:
        - $ref: "#/components/parameters/CaseId"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CollectionAction"
      responses:
        "201": { description: 行为已记录 }
      security: [{ AdminJWT: [] }]
      x-permissions: [{ role: collector, scope: collection.workbench }]
  /notifications/send:
    post:
      tags: [Notifications]
      summary: 触达借款人（模板化）
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/NotificationTask"
      responses:
        "202": { description: 已入队 }
      security: [{ ServiceJWT: [] }, { AdminJWT: [] }]
      x-permissions:
        - { role: service, scope: notify.auto }
        - { role: operator, scope: notify.broadcast }
  /channels/attributions:
    post:
      tags: [Channels]
      summary: 归因回传（Kochava→channel-svc）
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AttributionPayload"
      responses:
        "204": { description: 已记录 }
      x-permissions: [{ role: partner, scope: channel.ingest }]
  /reports/daily:
    get:
      tags: [Reports]
      summary: 平台每日统计（KPI）
      parameters:
        - in: query
          name: businessDate
          schema: { type: string, format: date }
          required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DailyReport"
      security: [{ AdminJWT: [] }]
      x-permissions: [{ role: analyst, scope: report.read }]

components:
  securitySchemes:
    BorrowerJWT:
      type: http
      scheme: bearer
      bearerFormat: JWT
    AdminJWT:
      type: http
      scheme: bearer
      bearerFormat: JWT
    ServiceJWT:
      type: http
      scheme: bearer
      bearerFormat: JWT
  parameters:
    IdempotencyKey:
      name: X-Idempotency-Key
      in: header
      required: true
      schema: { type: string, minLength: 8, maxLength: 128 }
      description: 幂等键，窗口 24h
    LoanId:
      name: loanId
      in: path
      required: true
      schema: { type: string }
    UserId:
      name: userId
      in: path
      required: true
      schema: { type: string }
    CaseId:
      name: caseId
      in: path
      required: true
      schema: { type: string }
  responses:
    Unauthorized:
      description: 未授权
      content:
        application/json:
          schema: { $ref: "#/components/schemas/Error" }
    TooManyRequests:
      description: 触发限流
      content:
        application/json:
          schema: { $ref: "#/components/schemas/Error" }
    Conflict:
      description: 资源冲突
      content:
        application/json:
          schema: { $ref: "#/components/schemas/Error" }
    Unprocessable:
      description: 参数合法但无法处理
      content:
        application/json:
          schema: { $ref: "#/components/schemas/Error" }
  schemas:
    UserProfile:
      type: object
      properties:
        userId: { type: string }
        phone: { type: string }
        level: { type: string, enum: [L1,L2,L3,L4,L5] }
        consents: { type: array, items: { type: string } }
        deviceFingerprints: { type: array, items: { type: string } }
        kycStatus: { type: string, enum: [pending, reviewing, approved, rejected] }
    KycPayload:
      type: object
      required: [docType, docNo, ocrResult, livenessScore]
      properties:
        docType: { type: string, enum: [ID_CARD, PASSPORT] }
        docNo: { type: string }
        ocrResult: { type: object, additionalProperties: true }
        livenessScore: { type: number, format: float }
        attachments: { type: array, items: { type: string, format: uri } }
    RiskEvaluationRequest:
      type: object
      required: [userId, loan, signals]
      properties:
        userId: { type: string }
        loan:
          type: object
          required: [loanId, amount, termDays, productId]
          properties:
            loanId: { type: string }
            amount: { type: string, pattern: "^[0-9]+(\\.[0-9]{1,4})?$" }
            termDays: { type: integer }
            productId: { type: string }
        signals:
          type: object
          properties:
            device: { type: object }
            kyc: { type: object }
            channel: { type: object }
    RiskEvaluationResult:
      type: object
      properties:
        decision: { type: string, enum: [APPROVE, REVIEW, REJECT] }
        score: { type: integer }
        reasons: { type: array, items: { type: string } }
        expiresAt: { type: string, format: date-time }
    LoanApplicationDraft:
      type: object
      required: [productId, requestedAmount, termDays]
      properties:
        productId: { type: string }
        requestedAmount: { type: string }
        termDays: { type: integer }
        purpose: { type: string }
    LoanSummary:
      type: object
      properties:
        loanId: { type: string }
        status: { $ref: "#/components/schemas/LoanStatus" }
        approvedAmount: { type: string }
        dueDate: { type: string, format: date }
        currency: { type: string }
    LoanStatus:
      type: string
      enum: [DRAFT,SUBMITTED,AUTO_CHECKING,AUTO_REJECTED,AUTO_APPROVED,MANUAL_REVIEW,MANUAL_REJECTED,APPROVED,CONTRACT_PENDING,CONTRACT_SIGNED,DISBURSE_PENDING,DISBURSED,ACTIVE,DUE_TODAY,OVERDUE,REPAID,WRITE_OFF]
    DisbursementRequest:
      type: object
      required: [loanId, amount, currency, channel, account]
      properties:
        loanId: { type: string }
        amount: { type: string }
        currency: { type: string, example: GHS }
        channel: { type: string, enum: [bank, wallet, card] }
        account:
          type: object
          required: [type, number]
          properties:
            type: { type: string, enum: [bank_account, momo, card] }
            number: { type: string }
            holderName: { type: string }
    RepaymentRequest:
      type: object
      required: [loanId, amount, currency, channel, txnRef]
      properties:
        loanId: { type: string }
        amount: { type: string }
        currency: { type: string }
        channel: { type: string }
        txnRef: { type: string }
        paidAt: { type: string, format: date-time }
    LedgerEntry:
      type: object
      required: [refType, refId, lines]
      properties:
        refType: { type: string, enum: [loan, repayment, fee] }
        refId: { type: string }
        lines:
          type: array
          items:
            type: object
            required: [account, debit, credit, currency]
            properties:
              account: { type: string }
              debit: { type: string }
              credit: { type: string }
              currency: { type: string }
              memo: { type: string }
    CollectionCaseCreate:
      type: object
      required: [loanId, userId, bucket, principalDue, currency]
      properties:
        loanId: { type: string }
        userId: { type: string }
        bucket: { type: string, enum: [D0,D1,D2,D3,D7,D15,D30,D60,WRITE_OFF] }
        principalDue: { type: string }
        currency: { type: string }
        source: { type: string, enum: [auto, manual] }
    CollectionAction:
      type: object
      required: [actionType, actor]
      properties:
        actionType: { type: string, enum: [CALL, SMS, FIELD_VISIT, NOTE, PTP] }
        actor: { type: string }
        note: { type: string }
        nextFollowUp: { type: string, format: date-time }
        ptpAmount: { type: string }
        ptpDate: { type: string, format: date }
    NotificationTask:
      type: object
      required: [channel, template, audience]
      properties:
        channel: { type: string, enum: [sms,email,push,whatsapp] }
        template: { type: string }
        audience:
          type: object
          properties:
            userId: { type: string }
            phone: { type: string }
        variables: { type: object, additionalProperties: true }
        sendAt: { type: string, format: date-time }
    AttributionPayload:
      type: object
      required: [installId, channel, event, occurredAt]
      properties:
        installId: { type: string }
        channel: { type: string }
        campaign: { type: string }
        event: { type: string, enum: [install, register, apply, disburse] }
        cost: { type: string }
        occurredAt: { type: string, format: date-time }
    DailyReport:
      type: object
      properties:
        businessDate: { type: string, format: date }
        currency: { type: string }
        metrics:
          type: object
          properties:
            registrations: { type: integer }
            applications: { type: integer }
            disbursements: { type: integer }
            disbursementAmount: { type: string }
            repayments: { type: integer }
            overdueRateD0: { type: number }
            rechurnRate: { type: number }
    Error:
      type: object
      properties:
        code: { type: string }
        message: { type: string }
        traceId: { type: string }
x-error-codes:
  - code: COMMON_400
    httpStatus: 400
    message: 请求参数错误
  - code: AUTH_401
    httpStatus: 401
    message: 鉴权失败
  - code: AUTH_429
    httpStatus: 429
    message: OTP 触发限流
  - code: LOAN_409
    httpStatus: 409
    message: 申请重复或状态冲突
  - code: PAYMENT_422
    httpStatus: 422
    message: 通道拒绝或余额不足
  - code: LEDGER_409
    httpStatus: 409
    message: 分录不平衡
  - code: COLLECTION_403
    httpStatus: 403
    message: 权限不足
